spring.application.name=api-gateway
server.port=8080

#G GATEWAY
spring.cloud.gateway.routes[0].filters[1]=RequestRateLimiter=redis-rate-limiter.replenishRate=10,redis-rate-limiter.burstCapacity=20

# ORDER SERVICE
spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# INVENTORY SERVICE
spring.cloud.gateway.routes[1].id=inventory-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/inventory/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# ACTUATOR
management.endpoints.web.exposure.include=*
management.endpoint.gateway.enabled=true

# LOG
logging.level.org.springframework.cloud.gateway=DEBUG