apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: {{ .Values.images.inventoryService }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.services.inventoryService.targetPort }}
          env:
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"