apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - port: {{ .Values.services.notificationService.port }}
      targetPort: {{ .Values.services.notificationService.targetPort }}
  type: {{ .Values.services.notificationService.type }}