apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.services.rabbitmq.amqpPort }}
      targetPort: {{ .Values.services.rabbitmq.amqpPort }}
    - name: management
      port: {{ .Values.services.rabbitmq.managementPort }}
      targetPort: {{ .Values.services.rabbitmq.managementPort }}
  type: {{ .Values.services.rabbitmq.type }}